inherit_gem:
  rubocop-config-umbrellio: lib/rubocop.yml

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 3.1
  SuggestExtensions: false

Naming/MethodParameterName:
  AllowedNames: ["x", "y", "z"]

RSpec/EmptyLineAfterHook:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Naming/FileName:
  Exclude:
    - lib/umbrellio-utils.rb

Naming/RescuedExceptionsVariableName:
  Enabled: false

Style/HashConversion:
  Exclude:
    - spec/**/*_spec.rb

Naming/VariableNumber:
  CheckSymbols: false

Naming/PredicateMethod:
  Enabled: false

require:
  - umbrellio_utils/rubocop

Custom/RegexRules:
  Enabled: true
