inherit_gem:
  rubocop-config-umbrellio: lib/rubocop.yml

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 3.1
  SuggestExtensions: false

Naming/MethodParameterName:
  AllowedNames: ["x", "y", "z"]

RSpec/EmptyLineAfterHook:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Naming/FileName:
  Exclude:
    - lib/umbrellio-utils.rb

Naming/RescuedExceptionsVariableName:
  Enabled: false

Style/HashConversion:
  Exclude:
    - spec/**/*_spec.rb

Naming/VariableNumber:
  CheckSymbols: false

Naming/PredicateMethod:
  Enabled: false

Custom/RegexRules:
  Enabled: true
  Rules:
    - name: Migrations/ProcessorsDirectDBAccess
      regex: 'DB\s*\[\s*:processors\s*\]'
      message: >
        Direct access to DB[:processors] is forbidden.
        Use Processor model and AfterDeploy job instead.
      paths:
        - db/migrate/**/*.rb
