inherit_gem:
  rubocop-config-umbrellio: lib/rubocop.yml

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.6

Naming/MethodParameterName:
  AllowedNames: ["x", "y", "z"]

RSpec/EmptyLineAfterHook:
  Enabled: false

Naming/FileName:
  Exclude:
    - lib/umbrellio-utils.rb

Naming/RescuedExceptionsVariableName:
  Enabled: false
